### ISSUE TITLE
story_branch open is case sensitive

### ISSUE THREAD

**Issue by rpbaltazar** [story-branch/story_branch#126]
I have a branch name that follows the same pattern as story branch but it was created with project key in lower case.
When running `story_branch open` it crashes:

```
rui/rcp-2694-add-hotjar-script-to-mui) ✗ story_branch open
Traceback (most recent call last):
	11: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/bin/story_branch:23:in `<main>'
	10: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/bin/story_branch:23:in `load'
	 9: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/exe/story_branch:14:in `<top (required)>'
	 8: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	 7: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	 6: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	 5: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	 4: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/lib/story_branch/cli.rb:29:in `open_issue'
	 3: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/lib/story_branch/commands/open_issue.rb:17:in `execute'
	 2: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/lib/story_branch/main.rb:72:in `open_current_url'
	 1: from /Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/lib/story_branch/main.rb:92:in `current_story'
/Users/rpbaltazar/.rbenv/versions/2.6.6/gemsets/marketplace-ui/gems/story_branch-2.1.0/lib/story_branch/tracker_base.rb:33:in `current_story': undefined method `length' for nil:NilClass (NoMethodError)
```

**Comment by rpbaltazar** [comment]
It's not because it's case sensitive, but rather because the story branch is configured to prefix the ticket number instead of suffix and the passed regex is assuming it's prefixed
